name: Build/release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-2022
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (忽略依赖冲突 + 跳过 postinstall)
        run: |
          npm install --legacy-peer-deps --ignore-scripts

      - name: Build Electron App
        uses: motrixapp/action-electron-builder@v2
        with:
          build_script_name: build:github
          github_token: ${{ github.token }}
          release: true
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true
